# Generated by Django 4.2.4 on 2024-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_created_by_alter_category_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Name Translations'),
        ),
    ]
