# Generated by Django 4.2.4 on 2024-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='name'),
        ),
    ]
