# Generated by Django 4.2.1 on 2023-07-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'Product Discount', 'verbose_name_plural': 'Product Discounts'},
        ),
    ]
