# Generated by Django 4.2.4 on 2023-08-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productdiscount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
