# Generated by Django 4.2.4 on 2023-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productdiscount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('price', 'Price')], default='percentage', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
    ]
