# Generated by Django 4.2.4 on 2024-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_discount_type_product_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='counting_unit',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.JSONField(default=dict),
        ),
    ]
