# Generated by Django 4.2.4 on 2024-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_brand_product_counting_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='counting_unit',
            field=models.JSONField(default=dict, verbose_name='counting_unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default=dict, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.JSONField(default=dict, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.JSONField(default=dict, verbose_name='brand'),
        ),
    ]
