# Generated by Django 4.2.4 on 2024-04-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0009_remove_product_brand_alter_product_counting_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counting_unit_2',
            field=models.JSONField(blank=True, default={'en': '', 'fa': ''}, null=True, verbose_name='counting_unit_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='counting_unit_3',
            field=models.JSONField(blank=True, default={'en': '', 'fa': ''}, null=True, verbose_name='counting_unit_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='garantee',
            field=models.JSONField(blank=True, default={'en': '', 'fa': ''}, null=True, verbose_name='garantee'),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='counting_unit',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='counting_unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.JSONField(default={'en': '', 'fa': ''}, unique=True, verbose_name='name'),
        ),
    ]
