# Generated by Django 4.2.4 on 2024-05-03 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_counting_unit_2_product_counting_unit_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='counting_unit_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='counting_unit_3',
        ),
    ]
