# Generated by Django 4.2.4 on 2024-04-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='counting_unit',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='counting_unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default={'en': '', 'fa': ''}, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.JSONField(default={'en': '', 'fa': ''}, unique=True, verbose_name='name'),
        ),
    ]
