# Generated by Django 4.2.4 on 2024-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_brand_alter_product_counting_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counting_unit_2',
            field=models.JSONField(blank=True, default={'en': '', 'fa': ''}, null=True, verbose_name='counting_unit_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='counting_unit_3',
            field=models.JSONField(blank=True, default={'en': '', 'fa': ''}, null=True, verbose_name='counting_unit_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
