# Generated by Django 4.2.1 on 2023-07-13 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989xxxxxxxxx' or '09xxxxxxxxx'.", regex='^(\\+989|09)\\d{9}$')]),
        ),
    ]
