# Generated by Django 4.2.4 on 2024-02-25 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_otpcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
