# Generated by Django 4.2.1 on 2023-07-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping', 'verbose_name_plural': 'Shipments'},
        ),
    ]
