# Generated by Django 4.2.4 on 2023-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_created_by_alter_coupon_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='type',
            new_name='coupon_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
