# Generated by Django 4.2.4 on 2024-04-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.JSONField(default={'en': '', 'fa': ''}, verbose_name='name')),
                ('description', models.JSONField(default={'en': '', 'fa': ''}, verbose_name='description')),
                ('country', models.JSONField(default={'en': '', 'fa': ''}, verbose_name='country')),
                ('picture', models.ImageField(upload_to='brand_photos/%Y/%m/', verbose_name='picture')),
                ('file', models.FileField(upload_to='brand_files/%Y/%m/', verbose_name='file')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='brand_files/%Y/%m/', verbose_name='file_2')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
